context:
  version: "0.4.104"

package:
  name: flyctl
  version: ${{ version }}

source:
  url: https://github.com/superfly/flyctl/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 9d4db7cd5adcaa4c224e53e6dcd9574fe356c162c9b62068007f156b9cc3d37f

build:
  number: 0
  script:
    interpreter: nu
    content:
      - let prefix = $env.LIBRARY_PREFIX? | default $env.PREFIX
      # build main app and generate license data
      - let build_time = date now | format date "%Y-%m-%dT%H:%M:%SZ"
      - let short_commit_hash = (http get https://api.github.com/repos/superfly/flyctl/commits/v${{ version }}).sha | str substring 0..6
      - go build -o=($prefix)/bin/ -v -ldflags=$'-s -w -X github.com/superfly/flyctl/internal/buildinfo.buildVersion=${{ version }} -X github.com/superfly/flyctl/internal/buildinfo.buildDate=($build_time) -X github.com/superfly/flyctl/internal/buildinfo.commit=($short_commit_hash)' -trimpath -tags production .
      - go-licenses save . --save_path=library_licenses --ignore=github.com/in-toto/attestation/go/v1 --ignore=github.com/in-toto/in-toto-golang --ignore=github.com/jmespath/go-jmespath --ignore=github.com/launchdarkly/go-jsonstream/v3 --ignore=github.com/launchdarkly/go-sdk-common/v3
      # generate shell completions
      - if: build_platform == host_platform
        then:
          - mkdir ($prefix)/share/bash-completion/completions ($prefix)/share/fish/vendor_completions.d ($prefix)/share/zsh/site-functions
          - let bin = ($prefix)/bin/flyctl
          - ^$bin completion bash | save ($prefix)/share/bash-completion/completions/flyctl
          - ^$bin completion fish | save ($prefix)/share/fish/vendor_completions.d/flyctl.fish
          - ^$bin completion zsh  | save ($prefix)/share/zsh/site-functions/_flyctl

requirements:
  build:
    - ${{ compiler("go-nocgo") }}
    - go-licenses
    - nushell

tests:
  - script:
      - flyctl help
      - flyctl version
  - package_contents:
      bin:
        - flyctl
      files:
        - if: unix and build_platform == host_platform
          then:
            - share/bash-completion/completions/flyctl
            - share/fish/vendor_completions.d/flyctl.fish
            - share/zsh/site-functions/_flyctl
        - if: win and build_platform == host_platform
          then:
            - Library/share/bash-completion/completions/flyctl
            - Library/share/fish/vendor_completions.d/flyctl.fish
            - Library/share/zsh/site-functions/_flyctl
      strict: true

about:
  summary: CLI for deploying and managing applications on fly.io
  description: |
    flyctl is the command-line interface for the fly.io platform for
    deploying and running applications on scalable hardware-isolated sandboxes.
    Use flyctl to launch apps, manage deployments, scale machines, handle
    secrets, configure networking, and more.
  license: Apache-2.0
  license_file:
    - LICENSE
    - library_licenses/
  homepage: https://fly.io
  repository: https://github.com/superfly/flyctl
  documentation: https://fly.io/docs/flyctl/

extra:
  recipe-maintainers:
    - salim-b
